name: CI

on:
  push:
    branches: [ main ]

jobs:

 
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run linter
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          docker-compose --profile test_profile up --exit-code-from lint lint
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          docker-compose --profile test_profile up --exit-code-from test test